[technote]
id = "SQR-098"
series_id = "SQR"
canonical_url = "https://sqr-098.lsst.io"
github_url = "https://github.com/lsst-sqre/sqr-098"
github_default_branch = "main"
date_created = 2025-03-04T19:03:12Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[[technote.authors]]
name.given = "Adam J."
name.family = "Thornton"
internal_id = "thorntonaj"
orcid = "https://orcid.org/0000-0001-9342-6032"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
